/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/project-lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Role-scoped paginated list of project lines */
        get: operations["listProjectLines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-lines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        /** Single project line detail */
        get: operations["getProjectLine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-lines/{id}/custom-ju": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a custom job unit to a project line estimation (BR-20)
         * @description Engineer/Admin only (BR-20). Creates a custom JU attached to the
         *     line's estimation. Custom JUs are not part of the workload standard.
         */
        post: operations["createCustomJU"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-lines/{id}/estimation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        /** Load existing estimation (inductors + JUs + yearly values + CPO comment) */
        get: operations["getEstimation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-lines/{id}/workload-standard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        /** Applicable inductors and JUs for the line */
        get: operations["getWorkloadStandard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-lines/{id}/estimation/draft": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save estimation as Draft (single line) */
        post: operations["saveEstimationDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-lines/{id}/estimation/definitive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save estimation as Definitive (single line) */
        post: operations["saveEstimationDefinitive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-lines/estimation/batch-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch save estimations as Draft (atomic, multi-line) */
        post: operations["batchSaveEstimationDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-lines/estimation/batch-definitive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch save estimations as Definitive (atomic, multi-line) */
        post: operations["batchSaveEstimationDefinitive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-lines/{id}/estimation/copy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copy estimation from a compatible source line */
        post: operations["copyEstimation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-lines/{id}/prototype": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        /** Load prototype quantities and comment */
        get: operations["getPrototype"];
        /** Save prototype quantities and comment */
        put: operations["savePrototype"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prototype-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active prototype categories */
        get: operations["listPrototypeCategories"];
        put?: never;
        /**
         * Create a prototype category
         * @description Admin only.
         */
        post: operations["createPrototypeCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prototype-categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Update a prototype category
         * @description Admin only.
         */
        put: operations["updatePrototypeCategory"];
        post?: never;
        /**
         * Delete a prototype category
         * @description Admin only. Returns 409 if category is in use.
         */
        delete: operations["deletePrototypeCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-lines/{id}/estimation/send-to-hvt": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send estimation to HVT (Stage 1)
         * @description PMO/Admin only. Sends project line estimation to HVT for CPO review.
         *     - Only lines with status=Estimated are sent (ERev-BR-04)
         *     - Sent status is irreversible (ERev-BR-02)
         */
        post: operations["sendToHvt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estimation/review/send-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Send all eligible Estimated lines to HVT (bulk, filtered view)
         * @description PMO/Admin only. Sends all lines with status=Estimated that match the
         *     provided filters. ERev-BR-05: send-all operates on the current filtered
         *     view only. ERev-BR-04: only Estimated lines are eligible.
         */
        put: operations["sendAllEstimatedToHvt"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hvt/stage2-callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * HVT CPO approval/rejection callback (Stage 2)
         * @description Service-to-service endpoint. HVT calls this after CPO review.
         *     Updates status to Approved or rejected per item.
         */
        post: operations["hvtStage2Callback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-lines/{id}/allocation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Bulk replace allocation for a project line
         * @description Replaces entire allocation. All job units must be provided.
         *     Only Admin/PMO/RCRC.
         */
        put: operations["putAllocation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Dirty-row save — update modified allocation rows only
         * @description Only sends modified rows. Cost_type cannot be changed (ALLOC-BR-10).
         *     TSA/TC without societe blocks save (ALLOC-BR-06).
         */
        patch: operations["patchAllocation"];
        trace?: never;
    };
    "/allocation/ju/{id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Split a job unit across multiple societes
         * @description Percentages must sum to 100% (ALLOC-BR-11).
         *     Each split inherits the cost_type from the original JU.
         */
        post: operations["splitAllocation"];
        /**
         * Undo split — restore original single row
         * @description Removes split children via CASCADE, restores parent (ALLOC-BR-12)
         */
        delete: operations["undoSplitAllocation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocation/bulk-assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Bulk assign societe to multiple job units
         * @description Overwrites existing societes on checked rows (ALLOC-BR-09).
         *     Cost_type never changes — inherits from original JU (ALLOC-BR-10).
         */
        patch: operations["bulkAssignAllocation"];
        trace?: never;
    };
    "/allocation/auto-rules-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview what auto-rules would assign to unassigned JUs
         * @description Admin/PMO only. Runs AllocationRuleMatcher on unassigned JUs (no societe) and
         *     returns the preview without persisting any changes (ALLOC-BR-02).
         */
        get: operations["getAllocationAutoRulesPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocation/ju/{id}/yearly-values": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        /** Yearly FTE and K€ breakdown for a job unit */
        get: operations["getJUYearlyValues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocation/rules/{metier}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Métier identifier */
                metier: components["parameters"]["PathMetier"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Upload allocation rules for a metier
         * @description Replaces all rules for this metier. If apply_on_upload=true,
         *     re-runs auto-rules on unassigned JUs (ALLOC-BR-02).
         *     Only Admin/PMO.
         */
        put: operations["putAllocationRules"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocation/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload K€ rates
         * @description Creates a new rate version with valid_from.
         *     Previous rates for same society_site+cost_type remain as history.
         *     Only Admin/PMO.
         */
        put: operations["putKEuroRates"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metier-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload metier distribution config
         * @description sp_pc + pc_co + co_sop must sum to 1.0.
         *     Creates a new version with valid_from.
         *     Only Admin/PMO.
         */
        put: operations["putMetierDistribution"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/final-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Approved project lines for the active cycle
         * @description PMO/Admin/RCRC/CPO. Returns all lines with status=Approved for the active cycle.
         *     FR-BR-03: byMetier breakdown uses only approved lines from this endpoint.
         */
        get: operations["getFinalReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/final-review/export-csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Final Review approved lines as flat CSV
         * @description PMO/Admin only. Exports all Approved lines for the active cycle.
         */
        get: operations["exportFinalReviewCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/final-review/send-stage3-hvt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send all approved lines to HVT (Stage 3)
         * @description PMO/Admin only. Sends entire active cycle.
         *     Non-blocking: can send with incomplete allocation (FR-BR-06).
         *     Warning returned for unallocated JUs.
         *     Resendable (FR-BR-07).
         */
        post: operations["sendStage3Hvt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/management/dashboard/pie-chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status distribution pie chart data
         * @description PMO/Admin only. Counts (PL, Métier) pairs per status.
         */
        get: operations["getPieChart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/management/dashboard/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status evolution timeline data
         * @description PMO/Admin only. Time series of status counts from status_change_log.
         */
        get: operations["getTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List estimation cycles (active + historical) */
        get: operations["listCycles"];
        put?: never;
        /**
         * Create new estimation cycle
         * @description PMO/Admin only. Auto-deactivates current active cycle (CYCLE-BR-04).
         *     No reactivation allowed (CYCLE-BR-02).
         */
        post: operations["createCycle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cycles/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current active cycle */
        get: operations["getActiveCycle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cycles/{id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        /** Summary statistics for a cycle (total lines, breakdown by status) */
        get: operations["getCycleSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workload-standard/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload workload standard (.xlsx, per metier)
         * @description Admin/RCRC only (WL-BR-01). Excel format only (WL-BR-02).
         *     Preprocessed and validated before commit (WL-BR-03).
         *     Creates new version, old versions retained (WL-BR-04).
         */
        post: operations["uploadWorkloadStandard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bulk-inductor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete inductors from a workload standard version (DEL-BR-01..10)
         * @description Admin/RCRC only. Deletes inductors from a specific workload standard version.
         *     DEL-BR-05: Cannot delete from the active version if it is the only version.
         *     DEL-BR-07: Deleting from a superseded version does not affect the active version.
         */
        delete: operations["bulkDeleteInductors"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workload-standard/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current active workload standard info */
        get: operations["getCurrentWorkloadStandard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/email-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Email send log for active cycle */
        get: operations["getEmailLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry a failed email send */
        post: operations["retryEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Metier: "H-DESIGN" | "H-TUNING" | "H-SOFTWARE" | "H-CUSTOMER" | "H-PROJECT" | "H-NP" | "H-TESTING";
        /** @enum {string} */
        Status: "To do" | "Draft" | "Estimated" | "Sent" | "Modification Requested" | "Approved";
        /** @enum {string} */
        CostType: "FTE" | "TSA" | "TC";
        ProjectLineListItem: {
            /** Format: uuid */
            id: string;
            /**
             * @description Unique identifier — composition of pl_number + metier (e.g. 'PL-016-Backend')
             * @example PL-016-Backend
             */
            project_id: string;
            name: string;
            metier: components["schemas"]["Metier"];
            status: components["schemas"]["Status"];
            /** Format: date-time */
            updated_at: string;
        };
        ProjectLineDetail: components["schemas"]["ProjectLineListItem"] & {
            description?: string;
            /** Format: date-time */
            created_at?: string;
            /** @description CPO rejection comment from last HVT Stage 2 callback */
            cpo_comment?: string | null;
            organ_type?: string | null;
            energy?: string | null;
            project_ranking?: string | null;
            injection_system?: string | null;
            alliance_code?: string | null;
            vehicle_code?: string | null;
            market?: string | null;
            standard_emissions?: string | null;
            client?: string | null;
            request_type?: string | null;
            engineering?: string | null;
            estimate_type?: string | null;
        };
        ProjectLineListResponse: {
            items: components["schemas"]["ProjectLineListItem"][];
            total: number;
        };
        /**
         * @description Unit of measurement for variable and fixed workload coefficients.
         * @enum {string}
         */
        UnitType: "man_day" | "bench_hours" | "kilometres" | "kiloeuros";
        JU: {
            id: string;
            /** @description Parent cran identifier. Denormalized for client convenience; also expressed structurally via Cran nesting in EstimationPayload. */
            cran_id?: string;
            /** @description Short display name (maps to ju_short_name in DB). */
            name: string;
            /** @description Full descriptive name (maps to ju_long_name in DB). */
            long_name?: string;
            /**
             * Format: float
             * @description Variable workload coefficient — man-days (or other unit) per occurrence unit.
             */
            variable?: number;
            /**
             * Format: float
             * @description Fixed workload component added once regardless of occurrence count.
             */
            fixed?: number;
            unit_type?: components["schemas"]["UnitType"];
            /** Format: float */
            occurrence: number;
            /**
             * @description When true, occurrence cannot be modified by the engineer (BR-09).
             * @default false
             */
            occurrence_locked: boolean;
            /** @description Function Major Module code. */
            fmm?: string;
            /** @description Sub Major Module code. */
            smm?: string;
            /** @description Detail Major Module code. */
            dmm?: string;
            /** @description Generic resource profile identifier. */
            generic_profile?: string;
            /** @default false */
            custom: boolean;
            /**
             * @description Routing métier. BH/KM → H-TESTING; else → matches project_line.metier.
             *     Set at save time and immutable after.
             * @enum {string}
             */
            metier: "H-DESIGN" | "H-TUNING" | "H-SOFTWARE" | "H-CUSTOMER" | "H-PROJECT" | "H-NP" | "H-TESTING";
        };
        Cran: {
            id: string;
            name: string;
            jus: components["schemas"]["JU"][];
        };
        Inductor: {
            id: string;
            name: string;
            crans: components["schemas"]["Cran"][];
        };
        EstimationPayload: {
            inductors: components["schemas"]["Inductor"][];
        };
        PreSaveSummary: {
            /** Format: float */
            total_fte: number;
            /** Format: float */
            total_bh: number;
            /** Format: float */
            total_km: number;
            yearly: {
                [key: string]: {
                    /** Format: float */
                    fte: number;
                    /** Format: float */
                    bh: number;
                    /** Format: float */
                    km: number;
                };
            };
        };
        SaveDraftResponse: {
            pre_save_summary: components["schemas"]["PreSaveSummary"];
        };
        CopyEstimationRequest: {
            /** Format: uuid */
            source_line_id: string;
        };
        BatchSaveRequest: {
            line_ids: string[];
            inductors: components["schemas"]["Inductor"][];
        };
        BatchSaveLineResult: {
            /** Format: uuid */
            line_id: string;
            summary: components["schemas"]["PreSaveSummary"];
        };
        BatchSaveResponse: {
            lines: components["schemas"]["BatchSaveLineResult"][];
        };
        WorkloadStandardResponse: {
            inductors: components["schemas"]["Inductor"][];
        };
        PrototypeCategoryEntry: {
            id: string;
            quantity: number;
        };
        PrototypePayload: {
            categories: components["schemas"]["PrototypeCategoryEntry"][];
            comment: string;
        };
        PrototypeCategory: {
            id: string;
            name: string;
        };
        HvtCallbackItem: {
            /** Format: uuid */
            project_line_id: string;
            metier: components["schemas"]["Metier"];
            approved: boolean;
            /** @description CPO rejection comment. Required when approved=false, ignored when approved=true. */
            comment?: string | null;
        };
        HvtCallbackRequest: components["schemas"]["HvtCallbackItem"][];
        HvtCallbackResultItem: {
            /** Format: uuid */
            project_line_id: string;
            success: boolean;
            error?: string | null;
        };
        HvtCallbackResponse: components["schemas"]["HvtCallbackResultItem"][];
        AllocationJU: {
            /** Format: uuid */
            id: string;
            societe: string;
            /** @description Optional. Defaults to the JU original cost_type. Never changes via bulk assign. */
            cost_type?: components["schemas"]["CostType"];
        };
        AllocationPutRequest: {
            job_units: components["schemas"]["AllocationJU"][];
        };
        AllocationPatchRequest: {
            job_units: components["schemas"]["AllocationJU"][];
        };
        KEuroCalculated: {
            /** Format: uuid */
            job_unit_id: string;
            year: string;
            /** Format: float */
            ke: number;
        };
        AllocationSaveResponse: {
            saved: number;
            keuro_calculated: components["schemas"]["KEuroCalculated"][];
        };
        SplitEntry: {
            societe: string;
            /** Format: float */
            percentage: number;
        };
        SplitRequest: {
            splits: components["schemas"]["SplitEntry"][];
        };
        SplitUndoResponse: {
            restored: boolean;
        };
        BulkAssignRequest: {
            job_unit_ids: string[];
            societe: string;
        };
        BulkAssignResponse: {
            saved: number;
            keuro_calculated: components["schemas"]["KEuroCalculated"][];
        };
        AllocationRuleEntry: {
            organ_type?: string | null;
            fuel_type?: string | null;
            ranking?: string | null;
            alliance_code?: string | null;
            vehicle_code?: string | null;
            standard_emissions?: string | null;
            market?: string | null;
            injection_system?: string | null;
            part_type?: string | null;
            society?: string;
            /** @default false */
            is_exception: boolean;
            /** @default 0 */
            priority: number;
            /** @default 0 */
            row_order: number;
        };
        AllocationRulesUploadRequest: {
            version: string;
            /**
             * @description If true, re-run auto-rules on unassigned JUs for this metier
             * @default false
             */
            apply_on_upload: boolean;
            rules: components["schemas"]["AllocationRuleEntry"][];
        };
        KEuroRateEntry: {
            society_site: string;
            cost_type: components["schemas"]["CostType"];
            year: number;
            /** Format: float */
            rate: number;
        };
        KEuroRatesUploadRequest: {
            /** Format: date */
            valid_from: string;
            rates: components["schemas"]["KEuroRateEntry"][];
        };
        MetierDistributionEntry: {
            metier: components["schemas"]["Metier"];
            /** Format: float */
            sp_pc: number;
            /** Format: float */
            pc_co: number;
            /** Format: float */
            co_sop: number;
        };
        MetierDistributionUploadRequest: {
            /** Format: date */
            valid_from: string;
            configs: components["schemas"]["MetierDistributionEntry"][];
        };
        Stage3SendRequest: {
            /** Format: uuid */
            cycle_id: string;
        };
        Stage3SendResponse: {
            /** @enum {string} */
            status: "Sent";
            lines_sent: number;
            /** @description Warning about incomplete allocation, if any */
            warning?: string | null;
        };
        PieChartSlice: {
            status: components["schemas"]["Status"];
            count: number;
            /** Format: float */
            percentage: number;
        };
        PieChartResponse: {
            total_pairs: number;
            slices: components["schemas"]["PieChartSlice"][];
        };
        TimelineDataPoint: {
            /** Format: date */
            date: string;
            status_counts: {
                [key: string]: number;
            };
        };
        TimelineResponse: {
            data_points: components["schemas"]["TimelineDataPoint"][];
        };
        CycleResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date */
            start_date: string;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        CreateCycleRequest: {
            name: string;
            /** Format: date */
            start_date: string;
        };
        CyclesListResponse: {
            items: components["schemas"]["CycleResponse"][];
        };
        WorkloadStandardCurrentResponse: {
            metier: components["schemas"]["Metier"];
            /** Format: uuid */
            version_id: string;
            version_number: string;
            /** Format: date-time */
            uploaded_at: string;
        };
        EmailLogItem: {
            /** Format: uuid */
            id: string;
            recipient_oid: string;
            /** @enum {string} */
            alert_type: "engineer_weekly" | "rcrc_weekly" | "rejection_notification";
            /** Format: uuid */
            cycle_id: string | null;
            success: boolean;
            error_detail?: string | null;
            /** Format: date-time */
            sent_at: string;
        };
        EmailLogResponse: {
            items: components["schemas"]["EmailLogItem"][];
        };
        EmailRetryRequest: {
            /** Format: uuid */
            email_log_id: string;
        };
        BulkDeleteInductorRequest: {
            /**
             * Format: uuid
             * @description Workload standard version to delete from (DEL-BR-05, DEL-BR-07).
             */
            version_id: string;
            inductor_ids: string[];
        };
        BulkDeleteResponse: {
            deleted: number;
            /** @description Non-blocking warnings (e.g. DEL-BR-05 active version protection). */
            warnings?: string[];
        };
        SendAllToHvtRequest: {
            /** Format: uuid */
            cycle_id: string;
            metier?: components["schemas"]["Metier"];
            /** @description Filter by assignee OID. Visible to PMO/Admin only (ERev-BR-06). */
            assignee?: string;
            /** @description Free-text filter on PL number or name (ERev-BR-05). */
            pl_number_name?: string;
        };
        SendAllToHvtResponse: {
            sent: number;
            skipped: number;
            warnings?: string[];
        };
        FinalReviewResponse: {
            items: components["schemas"]["ProjectLineListItem"][];
            total: number;
        };
        AutoRulesPreviewItem: {
            /** Format: uuid */
            job_unit_id: string;
            suggested_societe: string;
            matched_rule_id?: string | null;
        };
        AutoRulesPreviewResponse: {
            items: components["schemas"]["AutoRulesPreviewItem"][];
        };
        JUYearlyValueItem: {
            year: number;
            /** Format: float */
            fte: number;
            /** Format: float */
            ke: number;
        };
        JUYearlyValuesResponse: {
            /** Format: uuid */
            job_unit_id: string;
            values: components["schemas"]["JUYearlyValueItem"][];
        };
        CycleSummaryResponse: {
            /** Format: uuid */
            cycle_id: string;
            total_lines: number;
            by_status: {
                [key: string]: number;
            };
        };
        CreatePrototypeCategoryRequest: {
            name: string;
        };
        UpdatePrototypeCategoryRequest: {
            name: string;
        };
        CustomJURequest: {
            /** @description Short display name. */
            name: string;
            /** @description Full descriptive name. */
            long_name?: string;
            /**
             * Format: float
             * @description Workload value for this JU (man-days per inductor occurrence).
             */
            occurrence: number;
            metier: components["schemas"]["Metier"];
        };
        ErrorResponse: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description State conflict (e.g., invalid status transition) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Unique identifier of the resource (UUID) */
        PathId: string;
        /** @description Métier identifier */
        PathMetier: components["schemas"]["Metier"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjectLines: {
        parameters: {
            query?: {
                status?: components["schemas"]["Status"];
                metier?: components["schemas"]["Metier"];
                project_id?: string;
                /** @description Filter by assignee OID. Only returned when role is PMO/Admin (ERev-BR-06). */
                assignee?: string;
                /** @description Free-text search on PL number or name (ERev grid filter). */
                pl_number_name?: string;
                sort?: "name" | "-name" | "status" | "-status" | "updated_at" | "-updated_at";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of project lines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectLineListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getProjectLine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project line detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectLineDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createCustomJU: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomJURequest"];
            };
        };
        responses: {
            /** @description Custom JU created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JU"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getEstimation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current estimation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimationPayload"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getWorkloadStandard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workload standard grouped by inductor → cran → JU */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkloadStandardResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    saveEstimationDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstimationPayload"];
            };
        };
        responses: {
            /** @description Draft saved, returns pre-save summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveDraftResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    saveEstimationDefinitive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstimationPayload"];
            };
        };
        responses: {
            /** @description Estimation saved as definitive, returns pre-save summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveDraftResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    batchSaveEstimationDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchSaveRequest"];
            };
        };
        responses: {
            /** @description All drafts saved atomically */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchSaveResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    batchSaveEstimationDefinitive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchSaveRequest"];
            };
        };
        responses: {
            /** @description All estimations saved as definitive atomically */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchSaveResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    copyEstimation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyEstimationRequest"];
            };
        };
        responses: {
            /** @description Estimation copied and returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimationPayload"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getPrototype: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prototype data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrototypePayload"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    savePrototype: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrototypePayload"];
            };
        };
        responses: {
            /** @description Prototype saved, returns updated data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrototypePayload"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listPrototypeCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active prototype categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrototypeCategory"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createPrototypeCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePrototypeCategoryRequest"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrototypeCategory"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    updatePrototypeCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePrototypeCategoryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrototypeCategory"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePrototypeCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    sendToHvt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sent to HVT successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "Sent";
                    };
                };
            };
            /** @description Line not in Estimated status or invalid state */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            /** @description HVT service unavailable or returned error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sendAllEstimatedToHvt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendAllToHvtRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendAllToHvtResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description HVT service unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hvtStage2Callback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HvtCallbackRequest"];
            };
        };
        responses: {
            /** @description Callback processed, returns per-line results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HvtCallbackResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    putAllocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocationPutRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationSaveResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    patchAllocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocationPatchRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationSaveResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    splitAllocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationSaveResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    undoSplitAllocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplitUndoResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    bulkAssignAllocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkAssignRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkAssignResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getAllocationAutoRulesPreview: {
        parameters: {
            query?: {
                /** @description Scope preview to a specific metier. Omit for all metiers. */
                metier?: components["schemas"]["Metier"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoRulesPreviewResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getJUYearlyValues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JUYearlyValuesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    putAllocationRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Métier identifier */
                metier: components["parameters"]["PathMetier"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocationRulesUploadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        rules_saved: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    putKEuroRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KEuroRatesUploadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        rates_saved: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    putMetierDistribution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetierDistributionUploadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        configs_saved: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getFinalReview: {
        parameters: {
            query?: {
                metier?: components["schemas"]["Metier"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalReviewResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    exportFinalReviewCsv: {
        parameters: {
            query?: {
                /** @description Defaults to active cycle if omitted. */
                cycle_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file download */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    sendStage3Hvt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Stage3SendRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stage3SendResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description HVT service unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPieChart: {
        parameters: {
            query?: {
                metier?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PieChartResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getTimeline: {
        parameters: {
            query?: {
                metier?: string;
                from_date?: string;
                to_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listCycles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CyclesListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCycle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCycleRequest"];
            };
        };
        responses: {
            /** @description Cycle created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getActiveCycle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getCycleSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource (UUID) */
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleSummaryResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadWorkloadStandard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    metier: components["schemas"]["Metier"];
                    /**
                     * Format: binary
                     * @description Excel file (.xlsx)
                     */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkloadStandardCurrentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    bulkDeleteInductors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDeleteInductorRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDeleteResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getCurrentWorkloadStandard: {
        parameters: {
            query?: {
                metier?: components["schemas"]["Metier"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkloadStandardCurrentResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getEmailLog: {
        parameters: {
            query?: {
                alert_type?: "engineer_weekly" | "rcrc_weekly" | "rejection_notification";
                recipient?: string;
                success?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailLogResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    retryEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRetryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
